# Generated by Django 3.0.3 on 2020-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('passw', models.CharField(max_length=40)),
            ],
        ),
    ]
