# Generated by Django 3.0.3 on 2020-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='contact',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
    ]
